const urls = {
  // baseurl: "https://api.globelinfotech.in/",
  baseurl: "http://localhost:3009/",
  client: "https://globelinfotech.in/",
  appName: "GLOBEL INFO TECH",
  image: "uploads/",
  file: "thisproofisSellerXYZ/",
  products: "products/",
  bulkProducts: "products/bulk-upload",
  bulkCategory: "setting/bulk-upload",
  setting: "setting/",
  report: "report/",
  adminreport: "report/ads",
  settingByname: "setting/byname/",
  editsetting: "setting/editwithlogo/",
  verifySeller: "setting/verify-seller/",
  sellers: "setting/all",
  uploadApp: "setting/upload-apk",
  config: "setting/config",
  sellerList: "setting/seller-list",
  login: "user/login/",
  signup: "user/register",
  verify: "user/verify",
  profile: "user/profile",
  order: "order/",
  editorder: "order/status",
  orderads: "order/ads",
  contact: "contact/",
  users: "user/",
  rechargeTransaction: "recharge-transaction/",
  addCash: "recharge-transaction/cash/",
  changePlan: "recharge-transaction/change-plan/",
  changeAddon: "recharge-transaction/change-addon/",
  closeAddon: "recharge-transaction/close-addon/",
  editUsers: "user/adminchange/",
  CREATE_ORDER: "create-order",
  case: "case/",
  support: "support/",
  address: "address/",
  transaction: "transaction/",
};

export default urls;
